version: "3.9"

services:
  nfc-service:
    build: .
    container_name: nfc-service
    env_file:
      - .env
    ports:
      - "8001:8000"
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: wailsalutem
      RABBITMQ_DEFAULT_PASS: wailsalutem