apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nfc-service
  namespace: wailsalutem-suite
subjects:
  - kind: ServiceAccount
    name: nfc-service
    namespace: wailsalutem-suite
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nfc-service
