apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nfc-service
  namespace: wailsalutem-suite
spec:
  to:
    kind: Service
    name: nfc-service
  port:
    targetPort: 80
  tls:
    termination: edge
